"""empty message

Revision ID: f7f42e500935
Revises: 8d2af365900f
Create Date: 2025-10-04 05:00:08.754782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7f42e500935'
down_revision: Union[str, Sequence[str], None] = '8d2af365900f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sessions', sa.Column('last_checkpoint_node_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sessions', 'last_checkpoint_node_name')
    # ### end Alembic commands ###
