"""
Prompt templates for the Deep Research AI Agent.

This module contains all prompt templates used by agent nodes.
"""

from .templates.planner_prompt import (
    BROAD_DISCOVERY_PROMPT,
    TARGETED_INVESTIGATION_PROMPT,
    CONNECTION_MINING_PROMPT,
    VALIDATION_PROMPT,
    get_prompt_for_iteration
)

from .templates.extractor_prompt import (
    EXTRACTION_SYSTEM_PROMPT,
    EXTRACTION_USER_PROMPT,
    BATCH_EXTRACTION_PROMPT
)

from .templates.validator_prompt import (
    VALIDATION_SYSTEM_PROMPT,
    CROSS_REFERENCE_PROMPT,
    CONTRADICTION_DETECTION_PROMPT,
    SOURCE_AUTHORITY_EVALUATION_PROMPT,
    SEMANTIC_SIMILARITY_GROUPING_PROMPT
)

__all__ = [
    "BROAD_DISCOVERY_PROMPT",
    "TARGETED_INVESTIGATION_PROMPT",
    "CONNECTION_MINING_PROMPT",
    "VALIDATION_PROMPT",
    "get_prompt_for_iteration",
    "EXTRACTION_SYSTEM_PROMPT",
    "EXTRACTION_USER_PROMPT",
    "BATCH_EXTRACTION_PROMPT",
    "VALIDATION_SYSTEM_PROMPT",
    "CROSS_REFERENCE_PROMPT",
    "CONTRADICTION_DETECTION_PROMPT",
    "SOURCE_AUTHORITY_EVALUATION_PROMPT",
    "SEMANTIC_SIMILARITY_GROUPING_PROMPT",
]
